[files]
extend-exclude = ["*.eps"]

[default.extend-words]
# Ignore IDAES
IDAES = "IDAES"
idaes = "idaes"
# Ignore ParmEst
Parmest = "Parmest"
parmest = "parmest"
ParmEst = "ParmEst"
Parm = "Parm"
# Ignore ND
ND = "ND"